# Generated by Django 5.1.2 on 2025-04-19 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('url', models.URLField(verbose_name='Ссылка на сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Название компании')),
                ('position', models.CharField(max_length=200, verbose_name='Название должности')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('format', models.CharField(choices=[('remote', 'Удаленно'), ('office', 'Очно'), ('hybrid', 'Гибридный')], max_length=20, verbose_name='Формат стажировки')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('url', models.URLField(verbose_name='Ссылка на стажировку')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('source_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.website', verbose_name='Сайт-источник')),
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки',
            },
        ),
    ]
