# Generated by Django 5.1.2 on 2025-04-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_internship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internship',
            unique_together={('source_website', 'content_hash')},
        ),
    ]
