# Generated by Django 5.1.2 on 2025-05-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_auto_20250420_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова')),
                ('max_pages', models.IntegerField(default=10, verbose_name='Максимальное количество страниц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_executed', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего выполнения')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'unique_together': {('city', 'keywords')},
            },
        ),
    ]
