# Generated by Django 5.1.2 on 2025-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Особый сайт'),
        ),
    ]
